[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  directory = "netlify/functions"

  [functions."check-status-changes"]
  schedule = "*/15 * * * *"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Notion-Version, Authorization, X-Requested-With"
    Access-Control-Allow-Methods = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    Access-Control-Max-Age = "86400"