[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  directory = "netlify/functions"
  # Netlify automatically provides environment context for Blobs

  [functions."check-status-changes"]
  schedule = "*/2 * * * *"

  [functions."upload-image"]
  # This function uses Netlify Blobs for file storage
  
  [functions."serve-blob"]
  # This function serves files from Netlify Blobs

# Explicitly enable Netlify Blobs
[blobs]
  # This ensures Netlify Blobs is available for the site

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Notion-Version, Authorization, X-Requested-With"
    Access-Control-Allow-Methods = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    Access-Control-Max-Age = "86400"

# Environment configuration for development
[context.dev.environment]
  # Netlify Blobs will be automatically configured during netlify dev
  NODE_ENV = "development"

[context.production.environment]
  # Netlify automatically provides NETLIFY_SITE_ID and authentication
  NODE_ENV = "production"